In [2]:
import pandas as pd
import os

# Define the folder path containing CSV files
folder_path = "smallSplit Result"

# Read the first file and capture column names
first_file = os.path.join(folder_path, "result0.csv")
df = pd.read_csv(first_file)
column_names = df.columns.tolist()  # Extract column names as a list

# Create an empty list to store DataFrames
all_dataframes = []

# Loop through all files in the folder
for filename in os.listdir(folder_path):
  filepath = os.path.join(folder_path, filename)
  
  # Skip processing the first file again
  if filename == "result0.csv":
    all_dataframes.append(df)

  # Read subsequent files without header row
  df = pd.read_csv(filepath, header=None, names=column_names)
  all_dataframes.append(df)

# Concatenate all DataFrames in the list
merged_df = pd.concat(all_dataframes, ignore_index=True)

# Print or save the merged DataFrame
print(merged_df)

# You can also save the merged DataFrame to a new CSV file
merged_df.to_csv("merged_data.csv", index=False)

      createdAtBlockNumber createdAtTimestamp  \
0                 20011236           2024-6-3
1                 20011221           2024-6-3
2                 20011185           2024-6-3
3                 20011172           2024-6-3
4                 20011170           2024-6-3
...                    ...                ...
33639             18912838           2024-1-1
33640             18912838           2024-1-1
33641             18912820           2024-1-1
33642             18912800           2024-1-1
33643             18912734           2024-1-1

                                               id            reserve0  \
0      0xa1057899dbe0890bbe6b4b6836fef4cc1fdac0b3         700000000.0
1      0xae9372c042320e9dc6291ec301a7d77988141e08                 0.0
2      0x7f5bfa55f183e540a16adc24dcb0108add3a80bc            6.959208
3      0x41b0187b816d8232cafc6a7cbb20dad8a9f97660            6.505719
4      0xf3c8a1f9a3bcf2e3194337f965dede33f56206b4                 0.0
...                                           ...                 ...
33639  0x806654d9aa891bf8c20a50204a54df967ef9089b  0.0109301779956196
33640  0x584283dd0f4d13515fdf708d5375737debf627b1               1e-09
33641  0xb367b359af40ec0ce065847b555d78a5c70be02b            2.64e-07
33642  0x69d8da1d4aaf49f8ab4809e0f2276c9c1d08329f                 0.0
33643  0x11ea09a70e0ada3e1bd1b4ac1ce5aaf463fe9921                 0.0

                reserve1          reserveETH         reserveUSD  \
0                  10.01               10.01       38148.208088
1               0.000001                 0.0                0.0
2      68539701939.54744           13.918416       53036.978402
3      3900120176.482058           13.011438       49584.719089
4                    0.0                 0.0                0.0
...                  ...                 ...                ...
33639   8852256.44702882  0.0218603559912392  50.46965350531252
33640  0.060000000000005   0.060000000000005   138.016852839244
33641            3.8e-15             7.6e-15        1.77066e-11
33642       3.198936e-10                 0.0            4.6e-15
33643           1.64e-14               1e-16          2.903e-13

              totalSupply txCount          reserve00  ... is_MEV  \
0                2.647074       1        700000000.0  ...   True
1                     0.0      25           0.000001  ...   True
2               21.779508      92  68539701939.54744  ...   True
3                4.971779     280  3900120176.482058  ...   True
4                     0.0       0                0.0  ...   True
...                   ...     ...                ...  ...    ...
33639  311.44823004794875     128   8852256.44702882  ...   True
33640                 0.0      44              1e-09  ...   True
33641                 0.0      21           2.64e-07  ...   True
33642                 0.0      85       3.198936e-10  ...   True
33643                 0.0     101           1.64e-14  ...   True

      active_period rugpull_method rugpull_timestamp rugpull_timestamp_date  \
0             25188           burn        1717442171    2024-06-03 19:16:11
1               204           burn        1717417007    2024-06-03 12:16:47
2             15828           burn        1717432199    2024-06-03 16:29:59
3            185700            NaN                 0    1970-01-01 00:00:00
4            226284            NaN                 0    1970-01-01 00:00:00
...             ...            ...               ...                    ...
33639       2775216            NaN                 0    1970-01-01 00:00:00
33640           444           burn        1704115655    2024-01-01 13:27:35
33641         21528           burn        1704136559    2024-01-01 19:15:59
33642          2400           burn        1704118415    2024-01-01 14:13:35
33643         27684           burn        1704141911    2024-01-01 20:45:11

       before_rugpull_Eth after_rugpull_Eth       rugpull_change  \
0               16.558104               0.0                 -1.0
1                1.332908               0.0                 -1.0
2                7.169208               0.0                 -1.0
3                     0.0               0.0                  NaN
4                     0.0               0.0                  NaN
...                   ...               ...                  ...
33639                 0.0               0.0                  NaN
33640  1.9200461396667063        6.0718e-14  -0.9999999999999684
33641  12.027281023658956         3.804e-15  -0.9999999999999996
33642   5.459649575933079             1e-18                 -1.0
33643   1.844475310483178           6.2e-17                 -1.0

      rugpull_proceeding_hour is_rugpull
0          6.996666666666667h       True
1       0.056666666666666664h       True
2         4.3966666666666665h       True
3                        0.0h      False
4                        0.0h      False
...                       ...        ...
33639                    0.0h      False
33640    0.11333333333333333h       True
33641                   5.98h       True
33642     0.6666666666666666h       True
33643                   7.69h       True

[33644 rows x 58 columns]

In [3]:
df = pd.read_csv('merged_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33644 entries, 0 to 33643
Data columns (total 58 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   createdAtBlockNumber        33644 non-null  object
 1   createdAtTimestamp          33644 non-null  object
 2   id                          33644 non-null  object
 3   reserve0                    33644 non-null  object
 4   reserve1                    33644 non-null  object
 5   reserveETH                  33644 non-null  object
 6   reserveUSD                  33644 non-null  object
 7   totalSupply                 33644 non-null  object
 8   txCount                     33644 non-null  object
 9   reserve00                   33644 non-null  object
 10  reserve11                   33644 non-null  object
 11  token0.id                   33644 non-null  object
 12  token0.name                 33635 non-null  object
 13  token0.symbol               33635 non-null  object
 14  token0.totalLiquidity       33644 non-null  object
 15  token0.txCount              33644 non-null  object
 16  token1.id                   33644 non-null  object
 17  token1.name                 33642 non-null  object
 18  token1.symbol               33642 non-null  object
 19  token1.totalLiquidity       33644 non-null  object
 20  token1.txCount              33644 non-null  object
 21  token00.id                  33644 non-null  object
 22  token00.name                33633 non-null  object
 23  token00.symbol              33633 non-null  object
 24  token00.totalLiquidity      33644 non-null  object
 25  token00.txCount             33644 non-null  object
 26  token11.id                  33644 non-null  object
 27  token11.name                33644 non-null  object
 28  token11.symbol              33644 non-null  object
 29  token11.totalLiquidity      33644 non-null  object
 30  token11.txCount             33644 non-null  object
 31  initial_Liquidity_Eth       33644 non-null  object
 32  initial_Liquidity_Token     33644 non-null  object
 33  last_transaction_timestamp  33644 non-null  object
 34  last_transaction_date       33644 non-null  object
 35  mint_count                  33644 non-null  object
 36  swap_count                  33644 non-null  object
 37  burn_count                  33644 non-null  object
 38  mint_mean_period            33644 non-null  object
 39  swap_mean_period            33644 non-null  object
 40  burn_mean_period            33644 non-null  object
 41  swapIn                      33644 non-null  object
 42  swapOut                     33644 non-null  object
 43  token_burn_ratio            33644 non-null  object
 44  lp_avg                      33644 non-null  object
 45  lp_std                      33644 non-null  object
 46  creator_holding_ratio       33644 non-null  object
 47  lp_lock_ratio               33644 non-null  object
 48  is_MEV                      33644 non-null  object
 49  active_period               33644 non-null  object
 50  rugpull_method              25801 non-null  object
 51  rugpull_timestamp           33644 non-null  object
 52  rugpull_timestamp_date      33644 non-null  object
 53  before_rugpull_Eth          33644 non-null  object
 54  after_rugpull_Eth           33644 non-null  object
 55  rugpull_change              25801 non-null  object
 56  rugpull_proceeding_hour     33644 non-null  object
 57  is_rugpull                  33644 non-null  object
dtypes: object(58)
memory usage: 14.9+ MB

C:\Users\tyagi\AppData\Local\Temp\ipykernel_1088\1911921901.py:1: DtypeWarning: Columns (0,3,4,5,6,7,8,9,10,14,15,19,20,24,25,29,30,31,32,33,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,51,53,54,55,57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('merged_data.csv')